### ISSUE TITLE
Install fails because of Yum URL slashes

### ISSUE THREAD

**Issue by regner** [ome/ansible-role-fluentd#6]
```
TASK [ome.fluentd : fluentd | yum repo] ****************************************
--- before
+++ after: /tmp/awx_1163_vkutdhdg/requirements_roles/ome.fluentd/files/yum-reposd-fluentd.repo
@@ -0,0 +1,6 @@
+# https://docs.fluentd.org/v1.0/articles/install-by-rpm
+[treasuredata]
+name=TreasureData
+baseurl=https://packages.treasuredata.com/3/redhat/\$releasever/\$basearch
+gpgcheck=1
+gpgkey=https://packages.treasuredata.com/GPG-KEY-td-agent
changed: [vm-t1-test]
TASK [ome.fluentd : fluentd | install] *****************************************
fatal: [vm-t1-test]: FAILED! => {"changed": false, "msg": "Failed to download metadata for repo 'treasuredata': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried", "rc": 1, "results": []}
```

If I take the base URL that is put into the .repo file, `https://packages.treasuredata.com/3/redhat/\8/\x86_64/repodata/repomd.xml`, and try load it I get a 404.

If I remove the extra `\` from the URL it loads fine.

Updating the .repo file with the removal of the `\` also works.

**Comment by sbesson** [comment]
Thanks for the report @regner. I think the `\` characters come directly from the official scripts mentioned https://docs.fluentd.org/installation/install-by-rpm. It looks like others have encountered similar issues on RHEL/CentOS 8 - https://github.com/treasure-data/omnibus-td-agent/issues/205#issuecomment-579672094.

Feel free to open a PR with your changes. Assuming the tests keep passing on CentOS 7 which is our current platform of deployment, this should be a straightforward patch release.
